def write_file():
    f = open("file.txt", "w")
    name = input("Enter the Employee Name: ")
    id = input("Enter the Employee id: ")
    designation = input("Enter the Employee designation: ")
    salary = int(input("Enter the Employee salary: "))
    f.write(name + "\n")
    f.write(id + "\n")
    f.write(designation + "\n")
    f.write(str(salary) + "\n")
    f.close()
print("Enter the Employee Name, id , designation and salary")
write_file()
f = open("file.txt", "r")
print("The Employee Name is: ", f.readline())
print("The Employee id is: ", f.readline())
print("The Employee designation is: ", f.readline())
print("The Employee salary is: ", f.readline())
f.close() 